### ISSUE TITLE
Warn: "Actions repository already exists" every run

### ISSUE THREAD

**Issue by SaintPeter** [TheDragonCode/laravel-actions#131]
### Environment

- PHP Version: 8.0.15
- Database Driver & Version: MariaDB 10.4.22
- Actions Version: 4.2.1
- Laravel Version: 9.52.5

### Issue description

Whenever I run the `php artisan actions` command I get a warning "Actions repository already exists".

My migration actions execute properly, but I get the warning none-the-less.

Looking at the source code it looks like the `Install` class is running the `handle` function which generates this warning every time.  It's unclear why it should run at all.

### Steps to reproduce

It's unclear, but I just updated from 2.x to using the `migrate:actions:upgrade` command to 3.x, then to 4.x.

**Comment by andrey-helldar** [comment]
Ignore this warning. This mechanic remained after the project used the migrations codebase from Laravel.

I'll fix it soon.
